In [7]:
import requests
import pandas as pd
import time
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# --- CONFIGURATION ---
# CONFIGURACIÓN https://www.strava.com/oauth/authorize?client_id=186916&response_type=code&redirect_uri=http://localhost/exchange_token&approval_prompt=force&scope=activity:read_all
# Copia tu 'Your Access Token' desde https://www.strava.com/settings/api
ACCESS_TOKEN = os.getenv("ACCESS_TOKEN")

def obtener_actividades_strava(token):
    url = "https://www.strava.com/api/v3/athlete/activities"
    headers = {'Authorization': f"Bearer {token}"}
    
    actividades = []
    page = 1
    per_page = 200 # Máximo permitido por página
    
    print("Descargando datos de Strava...")
    
    while True:
        params = {'per_page': per_page, 'page': page}
        response = requests.get(url, headers=headers, params=params)
        
        if response.status_code != 200:
            print(f"Error: {response.status_code}")
            break
            
        data = response.json()
        
        if not data:
            break # No hay más actividades
            
        actividades.extend(data)
        print(f"Página {page} procesada ({len(data)} actividades)")
        page += 1
        
    return pd.DataFrame(actividades)

In [8]:
df = obtener_actividades_strava(ACCESS_TOKEN)

Descargando datos de Strava...
Error: 401

In [13]:
df.columns

Index(['resource_state', 'athlete', 'name', 'distance', 'moving_time',
       'elapsed_time', 'total_elevation_gain', 'type', 'sport_type',
       'workout_type', 'device_name', 'id', 'start_date', 'start_date_local',
       'timezone', 'utc_offset', 'location_city', 'location_state',
       'location_country', 'achievement_count', 'kudos_count', 'comment_count',
       'athlete_count', 'photo_count', 'map', 'trainer', 'commute', 'manual',
       'private', 'visibility', 'flagged', 'gear_id', 'start_latlng',
       'end_latlng', 'average_speed', 'max_speed', 'average_watts',
       'max_watts', 'weighted_average_watts', 'device_watts', 'kilojoules',
       'has_heartrate', 'average_heartrate', 'max_heartrate',
       'heartrate_opt_out', 'display_hide_heartrate_option', 'elev_high',
       'elev_low', 'upload_id', 'upload_id_str', 'external_id',
       'from_accepted_tag', 'pr_count', 'total_photo_count', 'has_kudoed',
       'average_temp'],
      dtype='object')

In [ ]:
df[['name', 'start_date_local', 'distance', 'moving_time', 
        'elapsed_time', 'total_elevation_gain', 'average_speed', 
        'max_speed', 'average_heartrate', 'max_heartrate']]

,name,start_date_local,distance,moving_time,elapsed_time,total_elevation_gain,average_speed,max_speed,average_heartrate,max_heartrate
6,Natación de mañana,2025-10-26T10:57:54Z,800.0,1251,1251,0.0,0.639,5.000,140.3,156.0
7,Natación a la hora del almuerzo,2025-10-11T12:22:12Z,500.0,836,836,0.0,0.598,5.000,126.8,139.0
10,Natación de noche,2025-09-26T18:10:14Z,500.0,796,796,0.0,0.628,2.778,146.5,150.0
11,Natación de mañana,2025-09-21T10:38:10Z,500.0,814,814,0.0,0.614,4.167,134.8,137.0
13,Natación de post gym,2025-09-05T14:25:21Z,500.0,797,797,0.0,0.627,5.000,132.2,142.0
14,Natación de noche,2025-08-22T18:28:27Z,387.0,582,582,14.2,0.665,0.970,140.7,145.0
16,Natación de tarde,2025-08-13T17:51:24Z,1000.0,1475,1475,0.0,0.678,5.000,138.9,146.0
18,Natación de tarde,2025-08-08T14:32:14Z,500.0,843,843,0.0,0.593,1.667,136.9,159.0
19,Natación de tarde,2025-08-04T14:03:37Z,600.0,920,920,0.0,0.652,2.273,136.1,140.0
22,Natación de mañana,2025-07-26T10:13:13Z,800.0,1125,1125,0.0,0.711,5.000,137.9,150.0
23,Natación de tarde,2025-07-24T16:58:35Z,800.0,1131,1131,0.0,0.707,5.000,146.5,161.0
24,Natación de tarde,2025-07-21T17:10:00Z,800.0,1242,1242,0.0,0.644,5.000,132.3,141.0
26,Natación de tarde,2025-07-17T13:30:55Z,500.0,789,789,0.0,0.634,0.862,129.6,138.0
29,Natación de tarde,2025-07-07T17:40:00Z,1500.0,2273,2273,0.0,0.660,5.000,138.2,156.0
30,Natación de tarde,2025-07-03T14:09:50Z,1000.0,1369,1369,0.0,0.730,5.000,126.7,157.0
31,Natación a la hora del almuerzo,2025-06-30T12:51:22Z,750.0,1135,1135,0.0,0.661,4.167,138.0,147.0
32,Natación de tarde,2025-06-25T17:42:09Z,1000.0,1745,1745,0.0,0.573,5.000,124.3,138.0
33,Natación de tarde,2025-06-23T17:47:05Z,800.0,1144,1144,0.0,0.699,4.167,131.0,148.0
35,Natación de tarde,2025-06-16T17:21:00Z,800.0,1232,1232,0.0,0.649,4.167,141.9,155.0
37,Natación de noche,2025-06-11T18:21:41Z,1250.0,1988,1989,0.0,0.629,5.000,125.5,145.0
41,Natación post gym,2025-05-11T11:40:29Z,750.0,1232,1232,0.0,0.609,5.000,143.8,155.0
46,Natación a la hora del almuerzo,2025-03-21T11:44:39Z,800.0,1338,1338,0.0,0.598,5.000,130.5,148.0
49,Natación de noche prepadel,2025-03-09T19:20:54Z,850.0,1201,1201,0.0,0.708,3.571,154.1,160.0
53,Natación de noche,2025-01-19T20:17:16Z,1000.0,1568,1568,0.0,0.638,5.000,143.1,152.0
61,Natación de noche,2024-12-05T20:58:24Z,1000.0,1539,1539,0.0,0.650,2.500,120.8,165.0
67,Long swim,2024-10-27T18:50:39Z,1500.0,2359,2359,0.0,0.636,0.926,141.9,146.0
71,Natación a la hora del almuerzo,2024-10-05T11:00:10Z,1000.0,1592,1592,0.0,0.628,4.167,135.9,148.0
73,Natación a la hora del almuerzo,2024-09-21T11:04:50Z,750.0,1152,1152,0.0,0.651,1.250,131.8,148.0
77,Natación post gym y carrera,2024-09-09T17:56:19Z,750.0,1135,1135,0.0,0.661,2.273,143.5,151.0
85,Natacion post gym 40 crol,2024-08-12T17:25:00Z,1000.0,1660,1660,0.0,0.602,5.000,136.0,150.0
94,20crol/10braza/10crol,2024-07-01T17:08:22Z,1000.0,1563,1563,0.0,0.640,4.167,127.7,144.0
128,Natación a la hora del almuerzo,2024-02-09T12:00:04Z,1000.0,1743,1743,0.0,0.574,5.000,130.1,142.0
141,Natación a la hora del almuerzo,2023-12-03T11:26:31Z,1000.0,1826,1826,0.0,0.548,5.000,135.3,160.0

:

In [12]:
df = df.loc[df['type'] == 'Swim']
df

,resource_state,athlete,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,...,elev_high,elev_low,upload_id,upload_id_str,external_id,from_accepted_tag,pr_count,total_photo_count,has_kudoed,average_temp
6,2,"{'id': 64019146, 'resource_state': 1}",Natación de mañana,800.0,1251,1251,0.0,Swim,Swim,NaN,...,0.0,0.0,17350480660,17350480660,34EF5188-B59A-431D-96BD-1EA963BF5742.fit,False,0,0,False,NaN
7,2,"{'id': 64019146, 'resource_state': 1}",Natación a la hora del almuerzo,500.0,836,836,0.0,Swim,Swim,NaN,...,0.0,0.0,17207902844,17207902844,294FCF1B-53C4-4C73-AFEA-82D2E536108E.fit,False,0,0,False,NaN
10,2,"{'id': 64019146, 'resource_state': 1}",Natación de noche,500.0,796,796,0.0,Swim,Swim,NaN,...,0.0,0.0,17048986629,17048986629,4D2C6BC1-68ED-4BDF-89EE-660083C4187D.fit,False,0,0,False,NaN
11,2,"{'id': 64019146, 'resource_state': 1}",Natación de mañana,500.0,814,814,0.0,Swim,Swim,NaN,...,0.0,0.0,17048987264,17048987264,94399573-4E28-495B-9FD1-CD90210F1145.fit,False,0,0,False,NaN
13,2,"{'id': 64019146, 'resource_state': 1}",Natación de post gym,500.0,797,797,0.0,Swim,Swim,NaN,...,0.0,0.0,16777061500,16777061500,BC50E5FB-F752-4956-A7C2-909032C4F42D.fit,False,0,0,False,NaN
14,2,"{'id': 64019146, 'resource_state': 1}",Natación de noche,387.0,582,582,14.2,Swim,Swim,NaN,...,0.6,-6.2,16606081689,16606081689,B21ED125-5CFF-4DD7-82AF-90591E4983C6.fit,False,0,0,False,NaN
16,2,"{'id': 64019146, 'resource_state': 1}",Natación de tarde,1000.0,1475,1475,0.0,Swim,Swim,NaN,...,0.0,0.0,16497412461,16497412461,027B8161-2F25-441C-9939-E876FFC346B6.fit,False,0,0,False,NaN
18,2,"{'id': 64019146, 'resource_state': 1}",Natación de tarde,500.0,843,843,0.0,Swim,Swim,NaN,...,0.0,0.0,16434196571,16434196571,8AF49BF4-331E-4145-B1E0-3122CADD48A0.fit,False,0,0,False,NaN
19,2,"{'id': 64019146, 'resource_state': 1}",Natación de tarde,600.0,920,920,0.0,Swim,Swim,NaN,...,0.0,0.0,16431114849,16431114849,620B3CF6-D6C5-4989-ABD6-F2D84428697F.fit,False,0,0,False,NaN
22,2,"{'id': 64019146, 'resource_state': 1}",Natación de mañana,800.0,1125,1125,0.0,Swim,Swim,NaN,...,0.0,0.0,16288028222,16288028222,A0833483-D190-47F4-8EAD-BEB66711DD81.fit,False,0,0,False,NaN
23,2,"{'id': 64019146, 'resource_state': 1}",Natación de tarde,800.0,1131,1131,0.0,Swim,Swim,NaN,...,0.0,0.0,16258762794,16258762794,940842F6-CE8D-4290-B365-FA37D11E5D03.fit,False,0,0,False,NaN
24,2,"{'id': 64019146, 'resource_state': 1}",Natación de tarde,800.0,1242,1242,0.0,Swim,Swim,NaN,...,0.0,0.0,16221451455,16221451455,A2ADC52F-7874-471D-AAC1-E37969B3AAE6.fit,False,0,0,False,NaN
26,2,"{'id': 64019146, 'resource_state': 1}",Natación de tarde,500.0,789,789,0.0,Swim,Swim,NaN,...,0.0,0.0,16179570269,16179570269,A4F55216-D2D2-4F17-B905-9E074C537E26.fit,False,0,0,False,NaN
29,2,"{'id': 64019146, 'resource_state': 1}",Natación de tarde,1500.0,2273,2273,0.0,Swim,Swim,NaN,...,0.0,0.0,16053674514,16053674514,7319F952-EFE5-4CED-9D82-F8AD9AE29C62.fit,False,0,0,False,NaN
30,2,"{'id': 64019146, 'resource_state': 1}",Natación de tarde,1000.0,1369,1369,0.0,Swim,Swim,NaN,...,0.0,0.0,16010513316,16010513316,A67BC82A-F39A-444E-87DB-6C11FB49E24A.fit,False,0,0,False,NaN
31,2,"{'id': 64019146, 'resource_state': 1}",Natación a la hora del almuerzo,750.0,1135,1135,0.0,Swim,Swim,NaN,...,0.0,0.0,15970725038,15970725038,18703D75-6E68-4E4E-B98F-A3E6CA34AF9F.fit,False,0,0,False,NaN
32,2,"{'id': 64019146, 'resource_state': 1}",Natación de tarde,1000.0,1745,1745,0.0,Swim,Swim,NaN,...,0.0,0.0,15925599794,15925599794,EC4F5685-D9AE-43F1-B23D-9C40F45568E4.fit,False,0,0,False,NaN
33,2,"{'id': 64019146, 'resource_state': 1}",Natación de tarde,800.0,1144,1144,0.0,Swim,Swim,NaN,...,0.0,0.0,15906162410,15906162410,05E0C4FA-4D78-42D0-A486-D1B32D56E3C4.fit,False,0,0,False,NaN
35,2,"{'id': 64019146, 'resource_state': 1}",Natación de tarde,800.0,1232,1232,0.0,Swim,Swim,NaN,...,0.0,0.0,15815049355,15815049355,EC80378B-ABCF-4939-86E5-27C64319F6D3.fit,False,0,0,False,NaN
37,2,"{'id': 64019146, 'resource_state': 1}",Natación de noche,1250.0,1988,1989,0.0,Swim,Swim,NaN,...,0.0,0.0,15767077598,15767077598,436D4019-1626-4324-85FF-CBB6528349F0.fit,False,0,0,False,NaN
41,2,"{'id': 64019146, 'resource_state': 1}",Natación post gym,750.0,1232,1232,0.0,Swim,Swim,NaN,...,0.0,0.0,15411813510,15411813510,4AF8D253-5152-4B54-96C9-765487312E9A.fit,False,0,0,False,NaN
46,2,"{'id': 64019146, 'resource_state': 1}",Natación a la hora del almuerzo,800.0,1338,1338,0.0,Swim,Swim,NaN,...,0.0,0.0,14900293848,14900293848,54D6BC79-FF03-431B-8501-37E2C097FF50.fit,False,0,0,False,NaN
49,2,"{'id': 64019146, 'resource_state': 1}",Natación de noche prepadel,850.0,1201,1201,0.0,Swim,Swim,NaN,...,0.0,0.0,14770497344,14770497344,B429CB94-72D8-49C0-8DFF-51EF4A33ED15.fit,False,0,0,False,NaN
53,2,"{'id': 64019146, 'resource_state': 1}",Natación de noche,1000.0,1568,1568,0.0,Swim,Swim,NaN,...,0.0,0.0,14293363027,14293363027,AAA210B8-9F20-4044-8AC1-9C0901DAECAD.fit,False,0,0,False,NaN
61,2,"{'id': 64019146, 'resource_state': 1}",Natación de noche,1000.0,1539,1539,0.0,Swim,Swim,NaN,...,0.0,0.0,13921891473,13921891473,57861092-CDD5-423C-B116-7E73AE22537D.fit,False,0,0,False,NaN
67,2,"{'id': 64019146, 'resource_state': 1}",Long swim,1500.0,2359,2359,0.0,Swim,Swim,NaN,...,0.0,0.0,13605761248,13605761248,DF322E0F-104C-47D2-A4CE-FB66696D1E5D.fit,False,0,0,False,NaN
71,2,"{'id': 64019146, 'resource_state': 1}",Natación a la hora del almuerzo,1000.0,1592,1592,0.0,Swim,Swim,NaN,...,0.0,0.0,13420075605,13420075605,6A419A9E-9E02-481B-A1D9-F4F6A4933942.fit,False,0,0,False,NaN
73,2,"{'id': 64019146, 'resource_state': 1}",Natación a la hora del almuerzo,750.0,1152,1152,0.0,Swim,Swim,NaN,...,0.0,0.0,13289994718,13289994718,9E2E58CE-583B-4B54-B623-F6EC5A39F022.fit,False,0,0,False,NaN
77,2,"{'id': 64019146, 'resource_state': 1}",Natación post gym y carrera,750.0,1135,1135,0.0,Swim,Swim,NaN,...,0.0,0.0,13186160408,13186160408,42F5EB1A-B46D-4AD4-A75F-132EF7770C68.fit,False,0,0,False,NaN
85,2,"{'id': 64019146, 'resource_state': 1}",Natacion post gym 40 crol,1000.0,1660,1660,0.0,Swim,Swim,NaN,...,0.0,0.0,12928156879,12928156879,F19F9146-10C3-43D0-8814-B2DD16036C51.fit,False,0,0,False,NaN
94,2,"{'id': 64019146, 'resource_state': 1}",20crol/10braza/10crol,1000.0,1563,1563,0.0,Swim,Swim,NaN,...,0.0,0.0,12568529895,12568529895,2E67359E-A4E5-4AC5-AE07-C9A7116D621B.fit,False,0,0,False,NaN
128,2,"{'id': 64019146, 'resource_state': 1}",Natación a la hora del almuerzo,1000.0,1743,1743,0.0,Swim,Swim,NaN,...,0.0,0.0,11490330295,11490330295,0A63DE13-25EF-43FA-89BA-B08493EBF1B3.fit,False,0,0,False,NaN
141,2,"{'id': 64019146, 'resource_state': 1}",Natación a la hora del almuerzo,1000.0,1826,1826,0.0,Swim,Swim,NaN,...,0.0,0.0,11063477959,11063477959,2288C191-153B-4123-B4CA-B2CE40D2F035.fit,False,0,0,False,NaN

In [5]:
df['type'].unique()

array(['Run', 'Swim', 'Ride', 'Hike', 'Workout', 'Walk', 'Handcycle'],
      dtype=object)

In [3]:
import streamlit as st
import pandas as pd
import os
def load_data(file_path):
    """Safely loads data from a CSV file."""
    if os.path.exists(file_path):
        try:
            return pd.read_csv(file_path)
        except Exception as e:
            st.error(f"Error loading {os.path.basename(file_path)}: {e}")
            return None
    return None

run_file = os.path.join('data', 'run.csv')
swim_file = os.path.join('data', 'swim.csv')
bike_file = os.path.join('data', 'bike.csv')

# Load datasets
run_df = load_data(run_file)
swim_df = load_data(swim_file)
bike_df = load_data(bike_file)

In [12]:

run_df['start_date_local'] = pd.to_datetime(run_df['start_date_local'])

In [15]:
run_df['start_date_local'].dt.year

0     2025
1     2025
2     2025
3     2025
4     2025
      ...
57    2021
58    2021
59    2021
60    2021
61    2021
Name: start_date_local, Length: 62, dtype: int32

In [19]:
run_df['Year'] = run_df["start_date_local"].dt.year
last_year_total_activities = len(run_df[run_df['Year']==2025])
last_year_total_activities

16

In [ ]:
run_df_distance = run_df[['start_date_local', 'distancel_km']]

KeyError: ('start_date_local', 'distancel_km')